import type { Metadata } from "next";
import { Slabo_27px } from "next/font/google";
import "./globals.css";
import CartProvider from "@/context/CartContext";
import { Toaster } from "sonner";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const slabo = Slabo_27px({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-slabo", // Optional: for Tailwind CSS
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${slabo.className} h-full antialiased`}>
      <CartProvider>
        <body className="min-h-full flex flex-col">
          <Navbar />
          <main className="flex-grow">{children}</main>
          <Footer />
          <Toaster
            position="bottom-right"
            toastOptions={{
              // This ensures the description text is visible against the dark background
              style: {
                background: "#3D2314",
                color: "#FCF9F5",
              },
            }}
          />
        </body>
      </CartProvider>
    </html>
  );
}
